# Generated by Django 5.0.3 on 2024-05-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariaAcudiente', '0001_initial'),
        ('secretariaEstudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='acudiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='secretariaAcudiente.acudiente'),
        ),
    ]
