# Generated by Django 5.0.3 on 2024-05-21 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretariaEstudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('idPersonal', models.AutoField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=20)),
                ('segundoNombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primerApellido', models.CharField(max_length=20)),
                ('segundoApellido', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='secretariaPersonal')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('idCargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariaPersonal.cargo')),
                ('idSede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariaEstudiante.sede')),
                ('idTipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='secretariaEstudiante.document')),
            ],
        ),
    ]
